name: Python CI

on:
  push:
    branches: [ main ] # Or your primary branch e.g., master
  pull_request:
    branches: [ main ] # Or your primary branch e.g., master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assumes you have a requirements.txt
        # If pytest or other test-specific deps are not in requirements.txt, install them:
        # pip install pytest testcontainers pymongo

    - name: Run tests
      run: |
        pytest